"""Add new mood dimensions and rename notes to journal

Revision ID: 19c981c4f72b
Revises: ebbb39146b0d
Create Date: 2025-05-12 10:47:57.217243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c981c4f72b'
down_revision = 'ebbb39146b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, add new columns with default values of 5
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('irritability', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('calmness', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('journal', sa.Text(), nullable=True))
    
    # Copy data from notes to journal
    connection = op.get_bind()
    connection.execute('UPDATE mood_entry SET journal = notes')
    
    # Now drop the notes column
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        # Add notes column back
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        
        # Copy data from journal to notes
        connection = op.get_bind()
        connection.execute('UPDATE mood_entry SET notes = journal')
        
        # Drop the new columns
        batch_op.drop_column('journal')
        batch_op.drop_column('calmness')
        batch_op.drop_column('irritability')
        batch_op.drop_column('focus')

    # ### end Alembic commands ###