"""Add is_public field to UploadedData

Revision ID: 80d45a144edd
Revises: 84270b31367d
Create Date: 2025-05-02 01:03:41.057255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d45a144edd'
down_revision = '84270b31367d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_data', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
