"""Add security question fields

Revision ID: ebbb39146b0d
Revises: 7b37823fcdec
Create Date: 2025-05-08 11:06:37.702760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbb39146b0d'
down_revision = '7b37823fcdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_question', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('secret_answer', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secret_answer')
        batch_op.drop_column('secret_question')

    # ### end Alembic commands ###
